server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          inventory-service:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: basic

logging:
  level:
    ru.yandex.practicum.order.feign.InventoryClient: DEBUG