server:
  port: 0

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timelimiter:
    configs:
      default:
        timeout-duration: 3s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          inventory-service:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: basic

logging:
  level:
    ru.yandex.practicum.order.feign.InventoryClient: DEBUG